### ISSUE TITLE
Make CI run on Mac as well

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/mclwrap#18]
Since we have been having some Mac-specific problems, it seems sensible to run the CI on MacOS as well. Github Actions seems to support running on MacOS via the [runs-on](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on) field. So should not be too hard to add.

**Comment by rheitjoh** [comment]
Can be easily added via
```yaml
runs-on: ${{ matrix.os }}

strategy:
    matrix:
        os: [ubuntu-latest, macos-latest]
```

However, we still use the old (v1.26) Mcl version where the Java FFI makefile's include path is incorrect for Mac OS.
So cannot add to CI at the moment.
